import {
    AlertTriangle,
    ShieldCheck,
} from "lucide-react";

export default function RiskCard({
    risk,
}) {
    if (!risk) {
        return null;
    }

    const level =
        risk.level || "LOW";

    const isSafe =
        level === "LOW";

    return (
        <div
            className={`risk-card risk-${level.toLowerCase()}`}
        >

            <div className="risk-card-header">

                <div className="risk-card-icon">

                    {isSafe ? (
                        <ShieldCheck size={24} />
                    ) : (
                        <AlertTriangle
                            size={24}
                        />
                    )}

                </div>

                <div>

                    <span>
                        WEATHER RISK
                    </span>

                    <h3>
                        {level}
                    </h3>

                </div>

                <div className="risk-score">
                    {risk.score ?? 0}
                </div>

            </div>

            <div className="risk-reasons">

                {risk.reasons?.length ? (
                    risk.reasons.map(
                        (reason, index) => (
                            <div
                                key={index}
                                className="risk-reason"
                            >
                                <span></span>
                                {reason}
                            </div>
                        )
                    )
                ) : (
                    <p>
                        No significant
                        weather risks
                        detected.
                    </p>
                )}

            </div>

            <div className="risk-source">
                Assessment generated by
                WeatherWatch
            </div>

        </div>
    );
}